[colors.primary]
background = "#242424"
foreground = "0xcdd6f4"

[font]
size = 15.0

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
opacity = 1

[window.padding]
x = 8
y = 8

[shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]
