set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# splits
unbind %
unbind '"'

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# windows
bind -r n next-window
bind -r p previous-window

bind c new-window -c "#{pane_current_path}"

# terminal
set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty:RGB"

# mouse
set -g mouse on

# faster vim / escape response
set -sg escape-time 0

set -g renumber-windows on

# reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# -------------------------------------------------
# STATUS BAR
# -------------------------------------------------

set -g status on
set -g status-position bottom
set -g status-interval 3
set -g status-justify left

set -g status-style "bg=#080b0a,fg=#b7c9b7"

# -------------------------------------------------
# WINDOWS
# -------------------------------------------------

# inactive
set -g window-status-format \
"#[fg=#53605a,bg=#080b0a] #I #[fg=#b7c9b7]#{b:pane_current_path} "

# active
set -g window-status-current-format \
"#[fg=#080b0a,bg=#39ff88,bold] #I #{b:pane_current_path} "

# separator
set -g window-status-separator ""

# -------------------------------------------------
# LEFT
# -------------------------------------------------

set -g status-left-length 50

set -g status-left \
"#[fg=#39ff88,bold] #(whoami) #[fg=#53605a]│ "

# -------------------------------------------------
# RIGHT
# -------------------------------------------------

set -g status-right-length 100

set -g status-right \
"#[fg=#53605a]│ #[fg=#5fffff] #S #[fg=#53605a]│ #[fg=#39ff88]%Y-%m-%d #[fg=#b7c9b7]󱑒 %H:%M "

set -g status-left-style none
set -g status-right-style none

# -------------------------------------------------
# PANES
# -------------------------------------------------

set -g pane-border-style "fg=#202820"
set -g pane-active-border-style "fg=#39ff88"

# -------------------------------------------------
# MESSAGES
# -------------------------------------------------

set -g message-style "bg=#080b0a,fg=#39ff88,bold"
set -g message-command-style "bg=#080b0a,fg=#5fffff"
